# Generated by Django 3.1 on 2020-09-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servesitems',
            options={'ordering': ['serves'], 'verbose_name': '服务项目记录', 'verbose_name_plural': '服务项目记录'},
        ),
        migrations.AlterModelOptions(
            name='servesmaids',
            options={'ordering': ['maid'], 'verbose_name': '服务女仆记录', 'verbose_name_plural': '服务女仆记录'},
        ),
        migrations.AlterModelOptions(
            name='servesplaces',
            options={'ordering': ['place'], 'verbose_name': '服务场所记录', 'verbose_name_plural': '服务场所记录'},
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maid',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='depositcharge',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='depositcharge',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='收费'),
        ),
        migrations.AlterField(
            model_name='maid',
            name='active',
            field=models.BooleanField(default=True, verbose_name='在职'),
        ),
        migrations.AlterField(
            model_name='maid',
            name='fulltime',
            field=models.BooleanField(default=False, verbose_name='全职'),
        ),
        migrations.AlterField(
            model_name='servescharge',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='servescharge',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='收费'),
        ),
    ]
