# Generated by Django 3.1 on 2020-09-02 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reception', '0002_auto_20200902_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'permissions': [('receive_money', '收钱')], 'verbose_name': '账单', 'verbose_name_plural': '账单'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'permissions': [('add_reservation', 'Can add a new reservation'), ('close_reservation', 'Can close a reservation')], 'verbose_name': '储值卡', 'verbose_name_plural': '储值卡'},
        ),
        migrations.AlterModelOptions(
            name='maidschedule',
            options={'ordering': ['date'], 'permissions': [('set_schedule', '可以给女仆排班')], 'verbose_name': '女仆排班', 'verbose_name_plural': '女仆排班'},
        ),
        migrations.AlterModelOptions(
            name='reserve',
            options={'permissions': [('add_reservation', 'Can add a new reservation'), ('close_reservation', 'Can close a reservation')], 'verbose_name': '预约', 'verbose_name_plural': '预约'},
        ),
        migrations.AlterModelOptions(
            name='serves',
            options={'permissions': [('check_in_serves', 'Can start a serves'), ('change_serves_status', 'Can change the status of a serves'), ('check_out_serves', 'Can check out serves')], 'verbose_name': '服务', 'verbose_name_plural': '服务'},
        ),
        migrations.AlterField(
            model_name='income',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
