# Generated by Django 3.1 on 2020-09-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_auto_20200902_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchertype',
            name='meituan',
            field=models.BooleanField(default=False, verbose_name='美团/大众'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='swift_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='流水号'),
        ),
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='meituan',
        ),
    ]
