# Generated by Django 3.1 on 2020-09-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_auto_20200902_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lounge',
            field=models.BooleanField(default=False, verbose_name='在大厅'),
        ),
        migrations.AlterField(
            model_name='depositcharge',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='收款'),
        ),
        migrations.AlterField(
            model_name='servescharge',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='收款'),
        ),
    ]
