# Generated by Django 3.1 on 2020-09-09 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_auto_20200908_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='servesmaids',
            name='overtime',
            field=models.BooleanField(default=False, verbose_name='加班'),
        ),
        migrations.AlterField(
            model_name='maid',
            name='identity',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='请输入正确的身份证号，包含数字和大写X', regex='^[0-9]{17}[0-9X]$')], verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='maid',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='active',
            field=models.BooleanField(default=False, verbose_name='赴约'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='advanced_payment',
            field=models.SmallIntegerField(default=0, verbose_name='定金'),
        ),
    ]
